skip_tags: true
clone_depth: 50

os: Visual Studio 2015

environment:
  matrix:
    # Conda builds
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86"
    - PY_MAJOR_VER: 2
      PYTHON_ARCH: "x86_64"
      SCIPY: "0.18"
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"
    # Pip builds
    - PYTHON: C:\Python27
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64


platform:
    - x64

build_script:
  - If Defined PY_MAJOR_VER ( tools\appveyor_conda.bat ) else ( tools\appveyor_pip.bat )
  - SET MKL_NUM_THREADS=1
  - SET NUMEXPR_NUM_THREADS=1
  - SET OMP_NUM_THREADS=1
  - pip install "pytest<4" pytest-xdist
  - python setup.py develop

test_script:
  # Remove xdist (-n auto) until warning reporting is working
  - pytest statsmodels
